### ISSUE TITLE
a_linearProgramsDefinition.pdf: in need of explanations regarding Equivalence relations

### ISSUE THREAD

**Issue by eliehalimi** [bashardudin/LinearPrograms#2]
Hello,

in the slides named 'Exemple of Equivalence Relations' is introduced on the right side a variable s. I was wondering what this variable was referring to. 
Furthermore, I was wondering why this inequality has now become an equality.

Here is the linear program:

minimize        	-2x1 -2x2 -3
subject to
		**-s + x1 + x2 + x3 = 4**
           		  x1 -  x2 -  x3  ≥ 2
       	 		- x1 + x2 + 2x3 ≥ 1
with               	  x1, x2, x3, s ≥ 0

Sincerely, 

Elie Halimi
BING 2021

**Comment by bashardudin** [comment]
Hey Elie, we haven't worked out this part during the course yet. We'll comment on it during todays course.
